# -*- coding: utf-8 -*-
"""Quarentena de Dados - Aula 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PDdEGVN11XCZktm_B_EirRpldDSFJqBe

#Aula 1

Formulando hipóteses e respondendo a essas perguntas.
"""

#Importando a base
import pandas as pd
base_imdb = pd.read_csv("https://raw.githubusercontent.com/llucaslleall/quarentena-dados/master/Bases/movie_metadata.csv")

#Verificando os valores distintos da coluna color
base_imdb["color"].unique()

#% em cada um dos valores acima (não considera o nan)
base_imdb["color"].value_counts(normalize=True)

#Contando o número de vezes que cada diretor aparece
base_imdb["director_name"].value_counts()

#Descrevendo a coluna num_critic_for_reviews
base_imdb["num_critic_for_reviews"].describe()

criticas = base_imdb["num_critic_for_reviews"]

#Plotando a informação de críticas
criticas.plot(kind="hist")

#Usando o gráfico do seaborn
import seaborn as sns
sns.distplot(criticas)

#Pegando os 5 primeiros com maior bilheteria
base_imdb.sort_values("gross",ascending=False).head()

#Pegando valores aleatórios
base_imdb.sample(10)

