# -*- coding: utf-8 -*-
"""Quarentena de Dados - Aula 0 e 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19JaClZU3jskAeTZ_cIc9FkCcO6L7xFe_

#Importação

Nesse trecho vamos importar as bases
"""

import pandas as pd

filmes = pd.read_csv("https://raw.githubusercontent.com/llucaslleall/quarentena-dados/master/Bases/movies.csv")

notas = pd.read_csv("https://raw.githubusercontent.com/llucaslleall/quarentena-dados/master/Bases/ratings.csv")

notas.columns = ["usuarioId","filmeId","nota","momento"]

filmes.columns = ["filmeId", "titulo", "generos"]

filmes.head()

"""# Testando as funções

Apenas testando algumas funções do pandas
"""

notas.query("filmeId == 1")

notas["nota"].mean()

notas.describe()



"""# Tratando os dados

Gerando a média e buscando o filme
"""

notas_medias = notas.groupby("filmeId")["nota"].mean()

filmes_medias = filmes.join(notas_medias, on="filmeId")

filmes_medias.sort_values("nota", ascending=False)

#Traçando o histograma dos dados
notas.query("filmeId == 2")["nota"].plot(kind="hist")



"""# Aula 2 - Tratando os dados

Tratando os dados recebidos
"""

filmes["generos"]

generos = filmes["generos"].str.get_dummies('|').sum()

generos = generos.sort_values(ascending=False)

generos.index

generos.values

generos.plot(kind="bar", title="generos", figsize=(10,5))
plt.show()

"""#Usando o seaborn"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.set_style("whitegrid")
plt.figure(figsize=(16,6))
sns.barplot(x=generos.index, y=generos.values, palette = sns.color_palette("BuGn_r", n_colors=len(generos)+5))
plt.show()

"""# Voltando na média

Voltando na média para também considerar a mediana
"""

filmes_medias

def plot_filme(n):
  notas_do_filme = notas.query(f"filmeId == {n}")["nota"]
  notas_do_filme.plot(kind="hist")
  plt.show()
  notas_do_filme.plot.box()
  plt.show()
  return notas_do_filme.describe()

plot_filme(919)

sns.boxplot(data = notas.query("filmeId in [1,2,919,46578]"),x="filmeId",y="nota")

